export enum ActionTypes {
  AuditsLoad = '[Audits] Load',
  AuditsLoadByUser = '[Audits] Load By User',
  AuditsSet = '[Audits] Set',
  FeatureToggleCreate = '[FeatureToggle] Create',
  FeatureToggleUpdate = '[FeatureToggle] Update',
  FeatureTogglesLoad = '[FeatureToggles] Load',
  FeatureTogglesSet = '[FeatureToggles] Set',
  TenantCreate = '[Tenant] Create',
  TenantSet = '[Tenant] Set',
  TenantUpdate = '[Tenant] Update',
  TenantUpdateAddUser = '[Tenant] Update Add User',
  TenantUpdateRemoveUser = '[Tenant] Update Remove User',
  TenantsLoad = '[Tenants] Load',
  TenantsSet = '[Tenants] Set',
  UserLoad = '[User] Load',
  UserSet = '[User] Set',
}
